// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmSubmitController from "./confirm_submit_controller.js"
application.register("confirm-submit", ConfirmSubmitController)

import SorterController from "./sorter_controller"
application.register("sorter", SorterController)

import SwapController from "./swap_controller.js"
application.register("swap", SwapController)
