// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ConfirmSubmitController from "./confirm_submit_controller.js"
application.register("confirm-submit", ConfirmSubmitController)

import PlayersController from "./players_controller.js"
application.register("players", PlayersController)

import SwapController from "./swap_controller.js"
application.register("swap", SwapController)
