version: "3"

x-app: &default_app
  image: loaded_questions:prod
  build:
    context: .
    dockerfile: docker/prod/Dockerfile
  environment:
    PGUSER: loaded_questions
    REDIS_URL: redis://loaded_questions_cache
  volumes:
    - loaded_questions_db_socket:/var/run/postgresql

volumes:
  loaded_questions_db_socket:
  loaded_questions_db_data:

services:
  loaded_questions:
    <<: *default_app
    command: ["bin/rails", "server", "--binding", "0.0.0.0", "--port", "3000"]
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - loaded_questions_db
      - loaded_questions_cache
      - loaded_questions_worker
  loaded_questions_db:
    image: postgres:15
    command: ["postgres", "-c", "listen_addresses="]
    restart: unless-stopped
    environment:
      POSTGRES_USER: loaded_questions
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - loaded_questions_db_socket:/var/run/postgresql
      - loaded_questions_db_data:/var/lib/postgresql/data
  loaded_questions_cache:
    image: redis:7
    restart: unless-stopped
  loaded_questions_worker:
    <<: *default_app
    command: ["bundle", "exec", "sidekiq"]
    restart: unless-stopped
    depends_on:
      - loaded_questions_db
      - loaded_questions_cache
