version: "3"

x-app: &default_app
  image: loaded_questions:dev
  build:
    context: .
    dockerfile: docker/dev/Dockerfile
  environment:
    PGHOST: /var/run/postgresql
    PGUSER: loaded_questions
    REDIS_URL: redis://cache
  volumes:
    - .:/app
    - vendor_bundle:/app/vendor/bundle
    - node_modules:/app/node_modules
    - db_socket:/var/run/postgresql

volumes:
  vendor_bundle:
  node_modules:
  db_socket:

services:
  web:
    <<: *default_app
    command: ["bin/rails", "server", "--binding", "0.0.0.0", "--port", "3000"]
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache
      - worker
      - css
      - js
  db:
    image: postgres:13
    command: ["postgres", "-c", "listen_addresses="]
    environment:
      POSTGRES_USER: loaded_questions
      POSTGRES_PASSWORD: loaded_questions_password
    volumes:
      - db_socket:/var/run/postgresql
  cache:
    image: redis:6
  worker:
    <<: *default_app
    command: ["bundle", "exec", "sidekiq"]
    depends_on:
      - db
      - cache
  css:
    <<: *default_app
    command: ["yarn", "build:css", "--watch"]
  js:
    <<: *default_app
    command: ["yarn", "build", "--watch"]
    stdin_open: true
