version: "3.1"

services:
  web:
    build: .
    command: ["bin/rails", "server"]
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: loaded_questions_password
    depends_on:
      - db
      - cache
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: loaded_questions_password
  cache:
    image: redis:6
