version: "3"

x-app: &default_app
  image: loaded_questions:prod
  build:
    context: .
    dockerfile: docker/prod/Dockerfile
  environment:
    PGHOST: /var/run/postgresql
    PGUSER: loaded_questions
    REDIS_URL: redis://loaded_questions_cache
  volumes:
    - loaded_questions_db_socket:/var/run/postgresql

volumes:
  loaded_questions_db_socket:

services:
  loaded_questions:
    <<: *default_app
    command: ["bin/rails", "server", "--binding", "0.0.0.0", "--port", "3000"]
    ports:
      - 3000:3000
    depends_on:
      - loaded_questions_db
      - loaded_questions_cache
      - loaded_questions_worker
  loaded_questions_db:
    image: postgres:13
    command: ["postgres", "-c", "listen_addresses="]
    environment:
      POSTGRES_USER: loaded_questions
      POSTGRES_PASSWORD: loaded_questions_password
    volumes:
      - loaded_questions_db_socket:/var/run/postgresql
  loaded_questions_cache:
    image: redis:6
  loaded_questions_worker:
    <<: *default_app
    command: ["bundle", "exec", "sidekiq"]
    depends_on:
      - loaded_questions_db
      - loaded_questions_cache
