version: "3"

services:
  web:
    image: loaded_questions
    build: .
    command: ["bin/rails", "server"]
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: loaded_questions_password
      REDIS_URL: redis://cache
    depends_on:
      - db
      - cache
      - worker
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: loaded_questions_password
  cache:
    image: redis:6
  worker:
    image: loaded_questions
    build: .
    command: ["bundle", "exec", "sidekiq"]
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: loaded_questions_password
      REDIS_URL: redis://cache
